### PR TITLE
Add Java 17 to CI

### PR DESCRIPTION
**Pull request by thc202**
Build with Java 17 which is a LTS version.
Disable tests that require JavaScript engine on Java 17+.

### CODE REVIEW

**Comment by psiinon** [comment]
Build failed?

**Comment by thc202** [comment]
Need to update the tests, they are expecting a JavaScript engine (Nashorn) which is no longer available in Java 17+.

**Comment by thc202** [comment]
Will update after the merge of #234, to use the newer JUnit annotations.

**Comment by thc202** [comment]
Done.

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Pull request merged**
