### PR TITLE
Update Gradle to 7.0

### PR DESCRIPTION
**Pull request by thc202**
Update Gradle Wrapper and build to 7.0.
Update Spotless to 5.12.1.
Migrate CI tweaks to GitHub, missed in #224.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
Browser tests are failing for some reason (they are passing locally).

**Comment by kingthorin** [comment]
Amend and push again?

**Comment by kingthorin** [comment]
Is checkout@v2 really usually the original v2 and not on of the newer versions that falls back to default branch? (Checking out master not main?) I haven’t read through the logs, sorry if it’s obvious.

**Comment by thc202** [comment]
Generally it should checkout the one that's being acted upon. (This repo no longer has the `master` branch.)

**Comment by kingthorin** [comment]
Agreed I just wondered if 2.0 had it hard coded because fallback wasn’t added till 2.3 or something like that.

**Comment by kingthorin** [comment]
Okay I finally read the log, I guess it isn’t checkout. The code is there and it is UnitTests which are failing.

**Comment by thc202** [comment]
Right, that's what I tried to say with https://github.com/zaproxy/zest/pull/227#issuecomment-822376525

**Comment by thc202** [comment]
This is now passing again (no changes...).

**Comment by kingthorin** [comment]
I'm fine with it being merged. It could have been something timing or infrastructure related.

**Comment by thc202** [comment]
Done :)

**Comment by thc202** [comment]
Build passed in `main` branch.

**Pull request merged**
